services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: githubxplainer
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
